/* This file should be replaced by element header generated by
 * gst-element-maker, or by your own source code.  To generate suitable
 * element header using gst-element-maker, run:
 *
 *   gst-element-maker  telemetry BASE_CLASS
 *
 * Where BASE_CLASS is replaced by one of the base class templates,
 * such as basesrc, basetransform, audiofilter, videofilter2, etc.
 * Then copy the resulting gsttelemetry.h file over this file, and
 * gsttelemetry.c over gsttelemetry.c.
 */
/* The rest of this file is shim code to allow the project to compile */
#define GST_TYPE_TELEMETRY G_TYPE_NONE
